version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - poetry run sphinx-build -b html docs/source/ docs/build/

python:
  install:
    - method: poetry
      path: .

sphinx:
  builder: custom
  configuration: docs/source/conf.py